In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [22]:
df.shape

(569, 33)

In [23]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [24]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [25]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [26]:
scaler = StandardScaler()                # scaling
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
encoder = LabelEncoder()                     # encoding
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [28]:
X_train

array([[ 1.17100555,  0.60783667,  1.1078745 , ...,  0.33394121,
         0.36096936, -0.43907811],
       [ 2.52081875,  1.71856097,  2.6737326 , ...,  2.38032939,
         0.50718631,  0.19323606],
       [ 2.16384336,  0.60550321,  2.20033364, ...,  1.92540854,
        -0.24361307,  0.0900459 ],
       ...,
       [-0.75610379, -2.00329882, -0.77236905, ..., -1.03762251,
         0.82262062, -0.53568167],
       [-1.00152437, -0.96957852, -1.0248485 , ..., -1.7502311 ,
        -0.29454256, -1.23276414],
       [-0.64454898, -0.2485411 , -0.69225538, ..., -0.79867571,
        -0.17132604, -0.54995265]], shape=(455, 30))

In [29]:
y_train

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [30]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [31]:
X_train_tensor.shape

torch.Size([455, 30])

In [32]:
y_train_tensor.shape

torch.Size([455])

In [33]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

In [35]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [36]:
train_dataset[10]

(tensor([-1.2478, -0.5402, -1.2268, -1.0395,  0.5323, -0.3957, -0.5848, -0.8102,
         -0.8320,  1.0907, -0.0212,  0.3868, -0.0691, -0.3845,  2.1962,  0.2267,
         -0.1596, -0.2477,  1.5730,  0.3228, -1.0970, -0.6806, -1.0776, -0.9143,
          0.6216, -0.5128, -0.6992, -0.9441, -0.5853,  0.0319]),
 tensor(0.))

In [37]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle=True)

## Define Model

In [46]:
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [47]:
epochs = 25
learning_rate = 0.1

In [55]:
# create model 
model = MyModel(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loss
loss_function = nn.BCELoss()

## Training pipeliine

In [57]:
# define loop
for epoch in range(epochs):
    for batch_feature, batch_label in train_loader:
        
        y_pred = model(batch_feature)    # Forward pass

        loss = loss_function(y_pred, batch_label.view(-1,1))  # Loss calculation

        optimizer.zero_grad()   # clear gradient

        loss.backward()    # Back propagation

        optimizer.step()   # parameters update

    
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')   # print loss in each epoch

Epoch: 1, Loss: 0.32953503727912903
Epoch: 2, Loss: 0.263258159160614
Epoch: 3, Loss: 0.07385232299566269
Epoch: 4, Loss: 0.1255045384168625
Epoch: 5, Loss: 0.12080316990613937
Epoch: 6, Loss: 0.16983890533447266
Epoch: 7, Loss: 0.0857401043176651
Epoch: 8, Loss: 0.18554480373859406
Epoch: 9, Loss: 0.051904525607824326
Epoch: 10, Loss: 0.030591310933232307
Epoch: 11, Loss: 0.013795665465295315
Epoch: 12, Loss: 0.01676677167415619
Epoch: 13, Loss: 0.08464036881923676
Epoch: 14, Loss: 0.09106071293354034
Epoch: 15, Loss: 0.057348959147930145
Epoch: 16, Loss: 0.051256515085697174
Epoch: 17, Loss: 0.002096180571243167
Epoch: 18, Loss: 0.06093925982713699
Epoch: 19, Loss: 0.060557179152965546
Epoch: 20, Loss: 0.010934731923043728
Epoch: 21, Loss: 0.03229369968175888
Epoch: 22, Loss: 0.12827150523662567
Epoch: 23, Loss: 0.1433142125606537
Epoch: 24, Loss: 0.20620271563529968
Epoch: 25, Loss: 0.05534067749977112

## Evaluation

In [59]:
model.eval()    # set the model to evaluation mode
accuracy_list = []


with torch.no_grad():
    for batch_feature, batch_label in test_loader:

        y_pred = model(batch_feature)     # forward pass
        y_pred = (y_pred > 0.8).float()   # Convert probabilities to binary predictions

        # calculate accuracy for the current batch
        batch_accuracy = (y_pred == batch_label).float().mean().item()
        accuracy_list.append(batch_accuracy)

# calculate overall accuracy
accuracy = sum(accuracy_list)/ len(accuracy_list)
print(f'Accuracy: {accuracy:.4f}')

Accuracy: 0.5812